version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  firefox:
    image: selenium/node-firefox:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - START_XVFB=false
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=10
    restart: unless-stopped

  selenium-hub:
    image: selenium/hub:4.9.1-20230508
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=30
      - SE_NODE_SESSION_TIMEOUT=30
    restart: unless-stopped

  scraper:
    build: .
    depends_on:
      - mongodb
      - selenium-hub

    volumes:
        - ./data:/app/data # subreddits.json

volumes:
  mongo_data: